# Generated by Django 5.1.6 on 2025-03-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='To‘liq ism')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('product', models.BigIntegerField(verbose_name='Mahsulot')),
                ('status', models.CharField(max_length=50, verbose_name='Holat')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('icon', models.CharField(max_length=255, verbose_name='Ikonka')),
                ('order', models.IntegerField(verbose_name='Tartib')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='To‘liq ism')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozim')),
                ('image', models.BigIntegerField(verbose_name='Rasm')),
                ('description', models.TextField(verbose_name='Tavsif')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.BigIntegerField(verbose_name='Rasm')),
                ('date', models.DateField(verbose_name='Sana')),
                ('body', models.TextField(verbose_name='Maqola')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255, verbose_name='Rasm')),
                ('url', models.CharField(max_length=255, verbose_name='Havola')),
                ('order', models.IntegerField(verbose_name='Tartib')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('status', models.CharField(max_length=255, verbose_name='Holat')),
                ('order', models.IntegerField(verbose_name='Tartib')),
                ('image', models.CharField(max_length=255, verbose_name='Rasm')),
                ('short_description', models.TextField(verbose_name='Qisqa tavsif')),
                ('description', models.TextField(verbose_name='Batafsil tavsif')),
                ('brand', models.BigIntegerField(verbose_name='Brend')),
                ('country', models.BigIntegerField(verbose_name='Mamlakat')),
                ('guarantee', models.BigIntegerField(verbose_name='Kafolat')),
                ('category', models.BigIntegerField(verbose_name='Kategoriya')),
                ('is_main_page', models.BooleanField(default=False, verbose_name='Asosiy sahifada')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Xususiyat nomi')),
                ('value', models.CharField(max_length=255, verbose_name='Qiymat')),
                ('order', models.BigIntegerField(verbose_name='Tartib')),
                ('product', models.BigIntegerField(verbose_name='Mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255, verbose_name='Rasm')),
                ('product', models.BigIntegerField(verbose_name='Mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='Yozmang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAIN_PAGE', models.CharField(max_length=255, verbose_name='Asosiy sahifa')),
                ('SERVICE', models.CharField(max_length=255, verbose_name='Xizmat')),
                ('GET_TT', models.CharField(max_length=255, verbose_name='TT olish')),
                ('PARTNER', models.CharField(max_length=255, verbose_name='Hamkor')),
                ('ORDER', models.BigIntegerField(verbose_name='Buyurtma')),
            ],
        ),
    ]
